# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
 use_frameworks!
pod 'AFNetworking'
pod 'ReactiveCocoa'
pod 'SDWebImage'
target 'swiftDemo' do

end

target 'swiftDemoTests' do

end

target 'swiftDemoUITests' do

end

